// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9j7B1M4N_6mEhHXxxbI0LzsZk_c-edY0',
    appId: '1:576391759280:web:70410fba5a612960c08275',
    messagingSenderId: '576391759280',
    projectId: 'bune-4b574',
    authDomain: 'bune-4b574.firebaseapp.com',
    storageBucket: 'bune-4b574.appspot.com',
    measurementId: 'G-YFFCD4D6FR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC59ZZHra-J-N_HlUarLtjyyganbQvK-NU',
    appId: '1:576391759280:android:28ee10c35491ef34c08275',
    messagingSenderId: '576391759280',
    projectId: 'bune-4b574',
    storageBucket: 'bune-4b574.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDERHrRFG-iWpzNS7uZHGsuteaDZ5_3jV4',
    appId: '1:576391759280:ios:0ada83a09bf3c759c08275',
    messagingSenderId: '576391759280',
    projectId: 'bune-4b574',
    storageBucket: 'bune-4b574.appspot.com',
    iosBundleId: 'com.example.bune',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDERHrRFG-iWpzNS7uZHGsuteaDZ5_3jV4',
    appId: '1:576391759280:ios:7bf57709c76f9fa0c08275',
    messagingSenderId: '576391759280',
    projectId: 'bune-4b574',
    storageBucket: 'bune-4b574.appspot.com',
    iosBundleId: 'com.example.bune.RunnerTests',
  );
}
